version: '3.8'

services:
  # NestJS service
  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: unless-stopped
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: 'postgresql://postgres:password@timescaledb:5432/mydatabase?schema=public'
    depends_on:
      - timescaledb

  # TimescaleDB service
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - '5432:5432'
    volumes:
      - timescale-data:/var/lib/postgresql/data

volumes:
  timescale-data:
